version : "3.8"

services:
  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    volumes:
     - ./mariadb/data:/var/lib/mysql
    env_file: Irex_drive/conf.defaults
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - docker_drive

  drive:
    image: drive
    container_name: drive
    restart: on-failure
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "2222:22"
      - "443:443"
      - "9000:9000"
      - "6379:6379"
    depends_on:
      - mariadb
    networks:
      - docker_drive

  drivesetup:
    image: drivesetup
    container_name: drivesetup
    restart: on-failure
    volumes:
      - ./Irex_drive/:/nextcloud/
    environment:
      - DRIVE_NGINX_PORT=80
      - DRIVE_SSH_PORT=2222
    depends_on:
      - drive
      - mariadb
    networks:
      - docker_drive

#network
# create a network 'drive' in mode 'bridged'
# networks:
#   docker_drive:
#     external: true

networks:
    docker_drive:
        driver: bridge
