---
- name: Clone a github repository
  git:
    repo: 'https://{{gituser}}:{{gitpass}}@gitface.irex.aretex.ca/irex-docker-projects/mirroring-iaas-projects/drive/nextcloud.git'
    dest: nextcloud
    clone: yes
    update: yes
    version: "{{ branch }}"