---
- name: Apt update cache
  apt:
    update_cache: yes

- name: add nginx apt-key
  apt_key: 
    url: "https://packages.sury.org/php/apt.gpg" 
    state: present 

- name: add nginx apt repository
  apt_repository: 
    repo: 'deb https://packages.sury.org/php/ buster main' 
    state: present 
    filename: "php{{ PHP_VERSION }}.list" 
    update_cache: yes

- name: Install  dependencies
  apt:
    name:
      - php{{PHP_VERSION}}
      - php{{PHP_VERSION}}-gd
      - php{{PHP_VERSION}}-mysql
      - php{{PHP_VERSION}}-curl
      - php{{PHP_VERSION}}-mbstring
      - php{{PHP_VERSION}}-intl
      - php{{PHP_VERSION}}-imagick
      - php{{PHP_VERSION}}-xml
      - php{{PHP_VERSION}}-zip
      - php{{PHP_VERSION}}-bcmath
      - php{{PHP_VERSION}}-gmp
      - php{{PHP_VERSION}}-fpm
      - php{{PHP_VERSION}}-gd
      - php{{PHP_VERSION}}-json
      - php{{PHP_VERSION}}-ldap
      - php{{PHP_VERSION}}-mysql
      - php{{PHP_VERSION}}-curl
      - php{{PHP_VERSION}}-mbstring
      - php{{PHP_VERSION}}-intl
      - php{{PHP_VERSION}}-xml
      - php{{PHP_VERSION}}-zip
      - php{{PHP_VERSION}}-sqlite3
      - php{{PHP_VERSION}}-imagick
      - php{{PHP_VERSION}}-common
      - python3-pymysql
    state: present