---
- name: install requirements for python
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true
  loop:
    - python3
    - python3-pip
- name: install docker for python
  apt:
    name: python3-docker
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true
- name: pip self-update
  pip:
    name: pip
    state: latest

- name: Install docker-compose python package
  pip:
    name: docker-compose